-- ============================================
-- SCRIPT PARA RECREAR TABLAS SIN AUTO_INCREMENT
-- Ejecutar en este orden para la carga inicial de datos
-- ============================================

-- 1. ELIMINAR LA FOREIGN KEY CONSTRAINT (si existe)
ALTER TABLE detalle_ventas DROP FOREIGN KEY IF EXISTS fk_venta;

-- 2. ELIMINAR LAS TABLAS (CUIDADO: Esto borra todos los datos)
DROP TABLE IF EXISTS detalle_ventas;
DROP TABLE IF EXISTS ventas_online;

-- 3. CREAR TABLA ventas_online SIN AUTO_INCREMENT
CREATE TABLE ventas_online (
    ID_VENTA INT PRIMARY KEY,
    ASESOR VARCHAR(100),
    ID_CLIENTE INT,
    CLIENTE VARCHAR(255),
    TIPO_COMPROBANTE VARCHAR(50),
    `N°_COMPR` VARCHAR(50),
    FECHA DATE,
    REGION VARCHAR(100),
    DISTRITO VARCHAR(100),
    FORMA_DE_PAGO VARCHAR(100),
    SALIDA_DE_PEDIDO VARCHAR(255),
    LINEA VARCHAR(100),
    CANAL_VENTA VARCHAR(100),
    CLASIFICACION VARCHAR(100)
);

-- 4. CREAR TABLA detalle_ventas SIN AUTO_INCREMENT
CREATE TABLE detalle_ventas (
    ID_DETALLE INT PRIMARY KEY,
    LINEA VARCHAR(100),
    CANAL_VENTA VARCHAR(100),
    `N°_COMPR` VARCHAR(50),
    CODIGO_PRODUCTO VARCHAR(50),
    PRODUCTO VARCHAR(255),
    CANTIDAD INT,
    UNIDAD_MEDIDA VARCHAR(50),
    PRECIO_VENTA DECIMAL(10,2),
    DELIVERY DECIMAL(10,2),
    TOTAL DECIMAL(10,2),
    ID_VENTA INT,
    CLASIFICACION VARCHAR(100),
    FECHA DATE,
    CONSTRAINT fk_venta FOREIGN KEY (ID_VENTA) REFERENCES ventas_online(ID_VENTA)
);

-- ============================================
-- DESPUÉS DE CARGAR LOS DATOS, EJECUTAR ESTO
-- PARA CONVERTIR A AUTO_INCREMENT:
-- ============================================

-- ALTER TABLE detalle_ventas DROP FOREIGN KEY fk_venta;
-- ALTER TABLE ventas_online MODIFY ID_VENTA INT NOT NULL AUTO_INCREMENT;
-- ALTER TABLE detalle_ventas MODIFY ID_DETALLE INT NOT NULL AUTO_INCREMENT;
-- ALTER TABLE detalle_ventas ADD CONSTRAINT fk_venta FOREIGN KEY (ID_VENTA) REFERENCES ventas_online(ID_VENTA);
